version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password

  backend:
    build: .
    container_name: recipe-backend
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    environment:

      # SPRING BOOT 기본 설정
      SERVER_PORT: 8080

      # DB
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # JPA 설정
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      # Mail
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

      # Gemini
      GEMINI_API_KEY: ${GEMINI_API_KEY}

      # GCP
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_PROCESSOR_ID: ${GCP_PROCESSOR_ID}
      GCP_PROCESSOR_LOCATION: ${GCP_PROCESSOR_LOCATION}
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json

      # FoodSafety Korea API
      FOODSAFETY_COOKRCP_BASE_URL: ${FOODSAFETY_COOKRCP_BASE_URL}
      FOODSAFETY_COOKRCP_SERVICE_KEY: ${FOODSAFETY_COOKRCP_SERVICE_KEY}

    ports:
      - "8080:8080"
    volumes:
      - "C:/keys/circular-curve-477214-c8-b2dc922f6afd.json:/app/gcp-key.json:ro"

volumes:
  mysql_data:
